### ISSUE TITLE
Migrate to sh

### ISSUE THREAD

**Issue by marcingrzejszczak** [marcingrzejszczak/jenkins-pipeline#2]
A Wilkinson: "I’d use `sh` rather than `bash` as the latter often isn’t available by default in lightweight Linux distros like Alpine. I discovered that the hard way when trying to build a Concourse Pipeline that uses Gradle which, unlike Maven, requires `bash`"

**Comment by making** [comment]
[making/alpine-java-bash-git](https://hub.docker.com/r/making/alpine-java-bash-git/) supports bash on alpine.
Isn't this enough?

**Comment by making** [comment]
[shinji62/alpine-docker-bash-git](https://github.com/shinji62/alpine-docker-bash-git) is smaller image without java.

**Comment by marcingrzejszczak** [comment]
That's what @awilkinson suggested in terms of scripts being generic

**Comment by marcingrzejszczak** [comment]
Andy Wilkinson :P
